import { readFile, readdir } from 'node:fs/promises'
import { basename, dirname, join, relative, sep } from 'node:path'
import { pathToFileURL } from 'node:url'

import { parseFrontmatter } from '@astrojs/markdown-remark'
import type { Loader } from 'astro/loaders'

const CONTENT_ROOT = join(process.cwd(), 'content', 'post')

// These IDs match the slugs generated by the old Hugo site. Keeping them here
// lets the new /blog URLs remain stable without changing any Markdown files.
const LEGACY_SLUGS: Record<string, string> = {
  '2024fall_学期总结': '2024fall-学期总结',
  '2025Fall_学期总结_上': '2025fall-学期总结-上',
  '2025spring_学期总结_上': '2025spring-学期总结-上',
  '2025spring_学期总结_下': '2025spring-学期总结-下',
  '2025summer_学期总结_上': '2025summer-学期总结-上',
  '2025总结': '2025总结',
  '2026spring_学期总结': '2026spring_学期总结',
  md测试: '测试中文',
  openGL学习: 'opengl学习',
  react学习: 'react学习笔记',
  '【Catlike Coding】Compute Shader': '2025spring-catlike-codingcompute-shader',
  不要变成AI大人的CV奴隶: '不要变成ai大人的cv奴隶',
  纸韵长安实习: 'paper-changan-internship',
  绘画临摹记录: '绘画临摹记录'
}

async function findMarkdownFiles(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true })
  const files: string[] = []
  for (const entry of entries) {
    const fullPath = join(directory, entry.name)
    if (entry.isDirectory()) files.push(...(await findMarkdownFiles(fullPath)))
    else if (entry.isFile() && entry.name.endsWith('.md')) files.push(fullPath)
  }
  return files
}

function firstParagraph(markdown: string) {
  const text = markdown
    .replace(/^\s*```[\s\S]*?```\s*/gm, '')
    .replace(/!\[[^\]]*\]\([^)]*\)/g, '')
    .replace(/[#>*`_~\-]/g, '')
    .split(/\n\s*\n/)
    .map((paragraph) => paragraph.replace(/\s+/g, ' ').trim())
    .find(Boolean)
  return text?.slice(0, 160)
}

function postId(filePath: string, data: Record<string, unknown>) {
  const folder = basename(dirname(filePath))
  const explicitSlug = typeof data.slug === 'string' ? data.slug.trim() : ''
  return explicitSlug || LEGACY_SLUGS[folder] || folder
}

export const hugoPostsLoader: Loader = {
  name: 'hugo-posts-loader',
  async load({ store, parseData, renderMarkdown, generateDigest, logger }) {
    const files = await findMarkdownFiles(CONTENT_ROOT)
    const seenIds = new Set<string>()

    for (const filePath of files) {
      const raw = await readFile(filePath, 'utf8')
      const parsed = parseFrontmatter(raw)
      const rawData = parsed.frontmatter as Record<string, unknown>
      const id = postId(filePath, rawData)
      if (seenIds.has(id)) {
        logger.error(`Duplicate blog slug "${id}" from ${filePath}`)
        continue
      }
      seenIds.add(id)

      const body = parsed.content
      const description =
        typeof rawData.description === 'string' && rawData.description.trim()
          ? rawData.description.trim()
          : firstParagraph(body) || String(rawData.title || id)
      const date = rawData.date ?? rawData.publishDate
      const categories = Array.isArray(rawData.categories) ? rawData.categories : []
      const tags = Array.isArray(rawData.tags) && rawData.tags.length ? rawData.tags : categories
      const title = String(rawData.title || id)
      const image = typeof rawData.image === 'string' ? rawData.image.trim() : ''

      // Astro resolves strings prefixed with __ASTRO_IMAGE_ through the
      // content asset map. This keeps Hugo's relative `image` value intact in
      // the source file while allowing Astro Pure's Hero/PostPreview
      // components to receive normal ImageMetadata at render time.
      const heroImage = image
        ? {
            src: /^(?:[a-z][a-z\d+.-]*:|\/)/i.test(image)
              ? image
              : `__ASTRO_IMAGE_${image}`,
            alt: title
          }
        : undefined

      const data = {
        ...rawData,
        title,
        description,
        publishDate: date,
        updatedDate: rawData.updatedDate,
        image: rawData.image,
        heroImage,
        tags,
        language: rawData.language || 'zh-CN',
        draft: rawData.draft === true,
        hidden: rawData.hidden === true,
        comment: rawData.comment === true || rawData.comments === true,
        slug: id
      }

      const parsedData = await parseData({
        id,
        data,
        filePath
      })

      // Custom loaders must render Markdown explicitly. Passing the original file
      // URL lets Astro/remark resolve relative image references against the Hugo
      // post directory while leaving the source bytes untouched.
      const rendered = await renderMarkdown(body, {
        fileURL: pathToFileURL(filePath)
      })

      store.set({
        id,
        data: parsedData,
        body,
        rendered,
        assetImports: rendered.metadata?.imagePaths,
        filePath: relative(process.cwd(), filePath).split(sep).join('/'),
        // Include the rendering contract in the digest so an existing local
        // content cache is refreshed after loader changes.
        digest: generateDigest(`${raw}\n<!-- astro-render-v2 -->`)
      })
    }
  }
}
